commit_message: '[ci skip]'
files:
  - source: /SharedResources/en.lproj/Localizable.strings
    translation: /SharedResources/%osx_code%/%original_file_name%
    skip_untranslated_strings: false
    skip_untranslated_files: true
  - source: /CryptomatorIntents/en.lproj/Intents.strings
    translation: /CryptomatorIntents/%osx_code%/%original_file_name%
    skip_untranslated_strings: false
    skip_untranslated_files: true
